//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agro.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agro.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Exit not found..
        /// </summary>
        public static string ANIMAL_EXIT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ANIMAL_EXIT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of animals must be greater than zero..
        /// </summary>
        public static string ANIMALS_MUST_BE_ABOVE_ZERO {
            get {
                return ResourceManager.GetString("ANIMALS_MUST_BE_ABOVE_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The departure date must be provided..
        /// </summary>
        public static string DEPARTURE_DATA_REQUIRED {
            get {
                return ResourceManager.GetString("DEPARTURE_DATA_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploration unit cannot be deleted with animals.
        /// </summary>
        public static string EXPLORATION_UNIT_CANNOT_BE_DELETED_WITH_ANIMALS {
            get {
                return ResourceManager.GetString("EXPLORATION_UNIT_CANNOT_BE_DELETED_WITH_ANIMALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploration Unit not found..
        /// </summary>
        public static string EXPLORATION_UNIT_NOT_FOUND {
            get {
                return ResourceManager.GetString("EXPLORATION_UNIT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The origin UEP must be different from the destination UEP..
        /// </summary>
        public static string ORIGIN_UEP_CANNOT_BE_DESTINATION_UEP {
            get {
                return ResourceManager.GetString("ORIGIN_UEP_CANNOT_BE_DESTINATION_UEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property code must be provided.
        ///.
        /// </summary>
        public static string PROPERTY_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("PROPERTY_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity exceeds available animals in source UEP..
        /// </summary>
        public static string QUANTITY_EXCEEDS_AVAILABLE_SOURCE_ANIMALS {
            get {
                return ResourceManager.GetString("QUANTITY_EXCEEDS_AVAILABLE_SOURCE_ANIMALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of animals must be provided..
        /// </summary>
        public static string QUANTITY_OF_ANIMALS_REQUIRED {
            get {
                return ResourceManager.GetString("QUANTITY_OF_ANIMALS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The species code must be provided.
        ///.
        /// </summary>
        public static string SPECIES_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("SPECIES_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The species does not exist..
        /// </summary>
        public static string THE_SPECIES_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("THE_SPECIES_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The departure UEP code must be provided.
        /// </summary>
        public static string UEP_DEPARTURE_REQUIRED {
            get {
                return ResourceManager.GetString("UEP_DEPARTURE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The origin UEP code must be provided..
        /// </summary>
        public static string UEP_ORIGIN_REQUIRED {
            get {
                return ResourceManager.GetString("UEP_ORIGIN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
